### ISSUE TITLE
Final CXapstone (KanBan SetUp)

### ISSUE THREAD

**Issue by Whoistolu** [chaw-bot/lease-a-home-API#29]
### In this issue, we:
Have Four (4) people in the team:
- [Chawanzi](https://github.com/chaw-bot)
- [Henry](https://github.com/HENRYKC24)
- [Tolu](https://github.com/Whoistolu)
- [Abdul](https://github.com/wuyepabdul)

Link to [Project](https://github.com/chaw-bot/lease-a-home-API) here.

### Screenshot for the board
![kanban](https://user-images.githubusercontent.com/58692590/155709772-22e11087-de10-4eb6-9b09-dcdd13aa49e6.png)

**Comment by MuriloRoque** [comment]
Hi @Whoistolu, @wuyepabdul, @HENRYKC24, @chaw-bot,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
